// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/karim-w/techunicorn-task/ent/predicate"
	"github.com/karim-w/techunicorn-task/ent/slot"
	"github.com/karim-w/techunicorn-task/ent/user"
)

// SlotUpdate is the builder for updating Slot entities.
type SlotUpdate struct {
	config
	hooks    []Hook
	mutation *SlotMutation
}

// Where appends a list predicates to the SlotUpdate builder.
func (su *SlotUpdate) Where(ps ...predicate.Slot) *SlotUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetPatientName sets the "patientName" field.
func (su *SlotUpdate) SetPatientName(s string) *SlotUpdate {
	su.mutation.SetPatientName(s)
	return su
}

// SetPatientId sets the "patientId" field.
func (su *SlotUpdate) SetPatientId(s string) *SlotUpdate {
	su.mutation.SetPatientId(s)
	return su
}

// SetAttendingName sets the "attendingName" field.
func (su *SlotUpdate) SetAttendingName(s string) *SlotUpdate {
	su.mutation.SetAttendingName(s)
	return su
}

// SetAttendingId sets the "attendingId" field.
func (su *SlotUpdate) SetAttendingId(s string) *SlotUpdate {
	su.mutation.SetAttendingId(s)
	return su
}

// SetStartTime sets the "startTime" field.
func (su *SlotUpdate) SetStartTime(t time.Time) *SlotUpdate {
	su.mutation.SetStartTime(t)
	return su
}

// SetEndTime sets the "endTime" field.
func (su *SlotUpdate) SetEndTime(t time.Time) *SlotUpdate {
	su.mutation.SetEndTime(t)
	return su
}

// SetStatus sets the "status" field.
func (su *SlotUpdate) SetStatus(s string) *SlotUpdate {
	su.mutation.SetStatus(s)
	return su
}

// SetAttendingDoctorID sets the "AttendingDoctor" edge to the User entity by ID.
func (su *SlotUpdate) SetAttendingDoctorID(id int) *SlotUpdate {
	su.mutation.SetAttendingDoctorID(id)
	return su
}

// SetNillableAttendingDoctorID sets the "AttendingDoctor" edge to the User entity by ID if the given value is not nil.
func (su *SlotUpdate) SetNillableAttendingDoctorID(id *int) *SlotUpdate {
	if id != nil {
		su = su.SetAttendingDoctorID(*id)
	}
	return su
}

// SetAttendingDoctor sets the "AttendingDoctor" edge to the User entity.
func (su *SlotUpdate) SetAttendingDoctor(u *User) *SlotUpdate {
	return su.SetAttendingDoctorID(u.ID)
}

// SetPatientID sets the "patient" edge to the User entity by ID.
func (su *SlotUpdate) SetPatientID(id int) *SlotUpdate {
	su.mutation.SetPatientID(id)
	return su
}

// SetNillablePatientID sets the "patient" edge to the User entity by ID if the given value is not nil.
func (su *SlotUpdate) SetNillablePatientID(id *int) *SlotUpdate {
	if id != nil {
		su = su.SetPatientID(*id)
	}
	return su
}

// SetPatient sets the "patient" edge to the User entity.
func (su *SlotUpdate) SetPatient(u *User) *SlotUpdate {
	return su.SetPatientID(u.ID)
}

// Mutation returns the SlotMutation object of the builder.
func (su *SlotUpdate) Mutation() *SlotMutation {
	return su.mutation
}

// ClearAttendingDoctor clears the "AttendingDoctor" edge to the User entity.
func (su *SlotUpdate) ClearAttendingDoctor() *SlotUpdate {
	su.mutation.ClearAttendingDoctor()
	return su
}

// ClearPatient clears the "patient" edge to the User entity.
func (su *SlotUpdate) ClearPatient() *SlotUpdate {
	su.mutation.ClearPatient()
	return su
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SlotUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		if err = su.check(); err != nil {
			return 0, err
		}
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SlotMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = su.check(); err != nil {
				return 0, err
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			if su.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *SlotUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SlotUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SlotUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SlotUpdate) check() error {
	if v, ok := su.mutation.PatientName(); ok {
		if err := slot.PatientNameValidator(v); err != nil {
			return &ValidationError{Name: "patientName", err: fmt.Errorf(`ent: validator failed for field "Slot.patientName": %w`, err)}
		}
	}
	if v, ok := su.mutation.PatientId(); ok {
		if err := slot.PatientIdValidator(v); err != nil {
			return &ValidationError{Name: "patientId", err: fmt.Errorf(`ent: validator failed for field "Slot.patientId": %w`, err)}
		}
	}
	if v, ok := su.mutation.AttendingName(); ok {
		if err := slot.AttendingNameValidator(v); err != nil {
			return &ValidationError{Name: "attendingName", err: fmt.Errorf(`ent: validator failed for field "Slot.attendingName": %w`, err)}
		}
	}
	if v, ok := su.mutation.AttendingId(); ok {
		if err := slot.AttendingIdValidator(v); err != nil {
			return &ValidationError{Name: "attendingId", err: fmt.Errorf(`ent: validator failed for field "Slot.attendingId": %w`, err)}
		}
	}
	if v, ok := su.mutation.Status(); ok {
		if err := slot.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Slot.status": %w`, err)}
		}
	}
	return nil
}

func (su *SlotUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   slot.Table,
			Columns: slot.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: slot.FieldID,
			},
		},
	}
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.PatientName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slot.FieldPatientName,
		})
	}
	if value, ok := su.mutation.PatientId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slot.FieldPatientId,
		})
	}
	if value, ok := su.mutation.AttendingName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slot.FieldAttendingName,
		})
	}
	if value, ok := su.mutation.AttendingId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slot.FieldAttendingId,
		})
	}
	if value, ok := su.mutation.StartTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: slot.FieldStartTime,
		})
	}
	if value, ok := su.mutation.EndTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: slot.FieldEndTime,
		})
	}
	if value, ok := su.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slot.FieldStatus,
		})
	}
	if su.mutation.AttendingDoctorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   slot.AttendingDoctorTable,
			Columns: []string{slot.AttendingDoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.AttendingDoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   slot.AttendingDoctorTable,
			Columns: []string{slot.AttendingDoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.PatientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   slot.PatientTable,
			Columns: []string{slot.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   slot.PatientTable,
			Columns: []string{slot.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{slot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// SlotUpdateOne is the builder for updating a single Slot entity.
type SlotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SlotMutation
}

// SetPatientName sets the "patientName" field.
func (suo *SlotUpdateOne) SetPatientName(s string) *SlotUpdateOne {
	suo.mutation.SetPatientName(s)
	return suo
}

// SetPatientId sets the "patientId" field.
func (suo *SlotUpdateOne) SetPatientId(s string) *SlotUpdateOne {
	suo.mutation.SetPatientId(s)
	return suo
}

// SetAttendingName sets the "attendingName" field.
func (suo *SlotUpdateOne) SetAttendingName(s string) *SlotUpdateOne {
	suo.mutation.SetAttendingName(s)
	return suo
}

// SetAttendingId sets the "attendingId" field.
func (suo *SlotUpdateOne) SetAttendingId(s string) *SlotUpdateOne {
	suo.mutation.SetAttendingId(s)
	return suo
}

// SetStartTime sets the "startTime" field.
func (suo *SlotUpdateOne) SetStartTime(t time.Time) *SlotUpdateOne {
	suo.mutation.SetStartTime(t)
	return suo
}

// SetEndTime sets the "endTime" field.
func (suo *SlotUpdateOne) SetEndTime(t time.Time) *SlotUpdateOne {
	suo.mutation.SetEndTime(t)
	return suo
}

// SetStatus sets the "status" field.
func (suo *SlotUpdateOne) SetStatus(s string) *SlotUpdateOne {
	suo.mutation.SetStatus(s)
	return suo
}

// SetAttendingDoctorID sets the "AttendingDoctor" edge to the User entity by ID.
func (suo *SlotUpdateOne) SetAttendingDoctorID(id int) *SlotUpdateOne {
	suo.mutation.SetAttendingDoctorID(id)
	return suo
}

// SetNillableAttendingDoctorID sets the "AttendingDoctor" edge to the User entity by ID if the given value is not nil.
func (suo *SlotUpdateOne) SetNillableAttendingDoctorID(id *int) *SlotUpdateOne {
	if id != nil {
		suo = suo.SetAttendingDoctorID(*id)
	}
	return suo
}

// SetAttendingDoctor sets the "AttendingDoctor" edge to the User entity.
func (suo *SlotUpdateOne) SetAttendingDoctor(u *User) *SlotUpdateOne {
	return suo.SetAttendingDoctorID(u.ID)
}

// SetPatientID sets the "patient" edge to the User entity by ID.
func (suo *SlotUpdateOne) SetPatientID(id int) *SlotUpdateOne {
	suo.mutation.SetPatientID(id)
	return suo
}

// SetNillablePatientID sets the "patient" edge to the User entity by ID if the given value is not nil.
func (suo *SlotUpdateOne) SetNillablePatientID(id *int) *SlotUpdateOne {
	if id != nil {
		suo = suo.SetPatientID(*id)
	}
	return suo
}

// SetPatient sets the "patient" edge to the User entity.
func (suo *SlotUpdateOne) SetPatient(u *User) *SlotUpdateOne {
	return suo.SetPatientID(u.ID)
}

// Mutation returns the SlotMutation object of the builder.
func (suo *SlotUpdateOne) Mutation() *SlotMutation {
	return suo.mutation
}

// ClearAttendingDoctor clears the "AttendingDoctor" edge to the User entity.
func (suo *SlotUpdateOne) ClearAttendingDoctor() *SlotUpdateOne {
	suo.mutation.ClearAttendingDoctor()
	return suo
}

// ClearPatient clears the "patient" edge to the User entity.
func (suo *SlotUpdateOne) ClearPatient() *SlotUpdateOne {
	suo.mutation.ClearPatient()
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SlotUpdateOne) Select(field string, fields ...string) *SlotUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Slot entity.
func (suo *SlotUpdateOne) Save(ctx context.Context) (*Slot, error) {
	var (
		err  error
		node *Slot
	)
	if len(suo.hooks) == 0 {
		if err = suo.check(); err != nil {
			return nil, err
		}
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SlotMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = suo.check(); err != nil {
				return nil, err
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			if suo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SlotUpdateOne) SaveX(ctx context.Context) *Slot {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SlotUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SlotUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SlotUpdateOne) check() error {
	if v, ok := suo.mutation.PatientName(); ok {
		if err := slot.PatientNameValidator(v); err != nil {
			return &ValidationError{Name: "patientName", err: fmt.Errorf(`ent: validator failed for field "Slot.patientName": %w`, err)}
		}
	}
	if v, ok := suo.mutation.PatientId(); ok {
		if err := slot.PatientIdValidator(v); err != nil {
			return &ValidationError{Name: "patientId", err: fmt.Errorf(`ent: validator failed for field "Slot.patientId": %w`, err)}
		}
	}
	if v, ok := suo.mutation.AttendingName(); ok {
		if err := slot.AttendingNameValidator(v); err != nil {
			return &ValidationError{Name: "attendingName", err: fmt.Errorf(`ent: validator failed for field "Slot.attendingName": %w`, err)}
		}
	}
	if v, ok := suo.mutation.AttendingId(); ok {
		if err := slot.AttendingIdValidator(v); err != nil {
			return &ValidationError{Name: "attendingId", err: fmt.Errorf(`ent: validator failed for field "Slot.attendingId": %w`, err)}
		}
	}
	if v, ok := suo.mutation.Status(); ok {
		if err := slot.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Slot.status": %w`, err)}
		}
	}
	return nil
}

func (suo *SlotUpdateOne) sqlSave(ctx context.Context) (_node *Slot, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   slot.Table,
			Columns: slot.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: slot.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Slot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, slot.FieldID)
		for _, f := range fields {
			if !slot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != slot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.PatientName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slot.FieldPatientName,
		})
	}
	if value, ok := suo.mutation.PatientId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slot.FieldPatientId,
		})
	}
	if value, ok := suo.mutation.AttendingName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slot.FieldAttendingName,
		})
	}
	if value, ok := suo.mutation.AttendingId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slot.FieldAttendingId,
		})
	}
	if value, ok := suo.mutation.StartTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: slot.FieldStartTime,
		})
	}
	if value, ok := suo.mutation.EndTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: slot.FieldEndTime,
		})
	}
	if value, ok := suo.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slot.FieldStatus,
		})
	}
	if suo.mutation.AttendingDoctorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   slot.AttendingDoctorTable,
			Columns: []string{slot.AttendingDoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.AttendingDoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   slot.AttendingDoctorTable,
			Columns: []string{slot.AttendingDoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.PatientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   slot.PatientTable,
			Columns: []string{slot.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   slot.PatientTable,
			Columns: []string{slot.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Slot{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{slot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
