// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Slot is the predicate function for slot builders.
type Slot func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
